## **Speed Test comparison of normal python and numpy**

In [ ]:
# Python Zip Explained
l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [ ]:
# Using Python Lists


import time

size = 1_000_000_0

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1, l2)]
end = time.time()
print(add[0:10])

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.8872220516204834


In [ ]:
# Using Numpy Arrays
import numpy as np
import time

size = 1_000_000_0

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2               #vectorized operations
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.05785322189331055


## **Creating Numpy Arrays**

In [ ]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


## **Memory Efficiency – NumPy vs. Lists**

In [ ]:
# With the help of nbytes we can detetct the size of the numpy arrays

import sys

list_data = list(range(1000))         #list

numpy_data = np.array(list_data)      #numpy array

print("Python list size:", sys.getsizeof(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056 bytes
NumPy array size: 8000 bytes


## **Vectorization – No More Loops!**

In [ ]:
# Squaring example

list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)

# Python list (loop-based)
list_squares = [x ** 2 for x in list1]
print(list_squares)


# NumPy (vectorized)
numpy_squares = arr1 ** 2
print(numpy_squares)

[1, 4, 9, 16, 25, 36]
[ 1  4  9 16 25 36]


# **Exercises for Practice**

In [ ]:
# Create a NumPy array with values from 10 to 100 and print its shape.

arr1 = np.array(list(range(10,100,1)))
arr2 = arr1.reshape(3, 30)
print(arr2)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
  64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93
  94 95 96 97 98 99]]


In [ ]:
import time as t
import numpy as np

list1 = [1,2,3,4,5,6,7,8,9]
list2 = [2,5,6,7,3,4,7,3,5]

arr1 = np.array(list1)
arr2 = np.array(list2)

# Multiply two python lists
startlisttime = t.time()
listmul = [x*y for x,y in zip(list1, list2)]
endlisttime = t.time()
print("List multiplication result:", listmul)
print("Time taken by list:", endlisttime - startlisttime)

# Multiply two numpy arrays
startarrtime = t.time()
arrmul = arr1 * arr2
endarrtime = t.time()
print("Array multiplication result:", arrmul)
print("Time taken by numpy:", endarrtime - startarrtime)


List multiplication result: [2, 10, 18, 28, 15, 24, 49, 24, 45]
Time taken by list: 9.72747802734375e-05
Array multiplication result: [ 2 10 18 28 15 24 49 24 45]
Time taken by numpy: 6.818771362304688e-05


In [ ]:
# Find the memory size of a NumPy array with 1 million elements.


size = 1_000_000

arr = np.array(list(range(size)))
print(f"One Million memory size is -> {arr.nbytes} bytes")

One Million memory size is -> 8000000 bytes


## **Creating Arrays from Scratch**

In [ ]:
 # 2x5 array of zeros

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 2x4 array of ones

np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Customised matrix with your inputs

np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.eye(4)                   # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(1, 10, 2)         # [1, 3, 5, 7, 9] (like range)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0, 1, 5)        # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## **Checking Array Properties**

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])


print("Shape:", arr.shape)                    # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)                      # 6 → total elements
print("Dimensions:", arr.ndim)                # 2 → 2D array
print("Data type:", arr.dtype)                # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


## **Changing Data Types**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)       # Explicit type
print(arr)
print(arr.dtype)                                  # float32


arr_int = arr.astype(np.int32)                    # Convert float to int
print(arr_int)                                    # [1 2 3]
print(arr_int.dtype)                              # int32

[1. 2. 3.]
float32
[1 2 3]
int32


## **Reshaping and Flattening Arrays**


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape) # (2, 3)

reshaped = arr.reshape((3, 2)) # Change shape
print(reshaped)

# [[1 2]
# [3 4]
# [5 6]]


flattened = arr.flatten() # Convert 2D → 1D
print(flattened) # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


## **Indexing and slicing**


In [ ]:
# Indexing

arr = np.array([10, 20, 30, 40])
print(arr[0]) # 10
print(arr[-1]) # 40

10
40


In [ ]:
# Slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4]) # [20 30 40] (slice from index 1 to 3)
print(arr[:3]) # [10 20 30] (first 3 elements)
print(arr[::2]) # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
# Slicing returns a view, not a copy! Changes affect the original array.

arr = np.array([10, 20, 30, 40, 50])
sliced = arr[1:4]
sliced[0] = 999
print(arr) # [10 999 30 40 50]

[ 10 999  30  40  50]


## **Fancy Indexing & Boolean Masking**



In [ ]:
# Fancy Indexing (Select Multiple Elements)

arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4] # Indices to select
print(arr[idx]) # [10 30 50]

[10 30 50]


In [ ]:
# Boolean Masking (Filter Data)

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25 # Condition: values greater than 25
print(arr[mask]) # [30 40 50]

[30 40 50]


# **Exercise**

In [ ]:
# Create a 3×3 array filled with random numbers and print its shape.

arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr.shape)

(3, 3)


In [ ]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers.

arr = np.array([1.1, 2.2, 3.3])
print(arr)
print(arr.dtype)

arr2 = arr.astype(np.int32)
print(arr2)
print(arr2.dtype)

[1.1 2.2 3.3]
float64
[1 2 3]
int32


In [ ]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[arr % 2 == 0])

[2 4 6]


In [ ]:
# Reshape a 1D array of size 9 into a 3×3 matrix.

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.shape)

reshaped = arr.reshape((3,3))
print(reshaped)
print(reshaped.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# Use boolean masking to filter numbers greater than 50 in an array.

arr = np.array(list(range(101)))
print(arr[arr > 50])

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## **Multidimensional Indexing and Axis**

In [ ]:
# Axes in a 2D Array


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr)
print()

print(np.sum(arr, axis=0)) # Sum along rows (down each column)
print(np.sum(arr, axis=1)) # Sum along columns (across each row

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]
[ 6 15 24]


In [ ]:
#  Indexing in Multidimensional Arrays

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[1, 2])       # Access element at row 1, column 2 (8)

print(arr[0:2, 1:3])   #also can be sliced

6
[[2 3]
 [5 6]]


In [ ]:
# Indexing in 3D Arrays

arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])


# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape) # Output: (2, 2, 3)


(2, 2, 3)


In [ ]:
# Accessing elements in 3D:

# First sheet, second row, third column
print(arr3D[0, 1, 2]) # Output: 6
print(arr3D[:, 0, :]) # Get the first row from both sheets


6
[[1 2 3]
 [7 8 9]]


In [ ]:
# Practical Example: Selecting Data Along Axes

# Get all rows of the first column

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

first_col = arr[:, 0]
print(first_col) # Output: [1 4 7]

[1 4 7]


In [ ]:
#  Changing Data Along an Axis

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[:, 0] = 10
print(arr)

[[10  2  3]
 [10  5  6]
 [10  8  9]]


## **Data Types in NumPy**


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype) # Output: int64 (or int32 depending on the system)

int32


## **Changing Data Types**


In [3]:
arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype) # Output: float64


arr_int = arr.astype(np.int32) # Converting float to int


print(arr_int) # Output: [1 2 3]
print(arr_int.dtype) # Output: int32

float64
[1 2 3]
int32


In [9]:
# Downcasting to Save Memory

arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype)
print(arr.nbytes)

arrdown = arr.astype(np.float32)
print(arrdown.dtype)
print(arrdown.nbytes)

float64
24
float32
12


In [11]:
# Complex numbers

arr = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


In [13]:
# Object Data type
# You need to mention dtype for storing objects in the numpy arrays

arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype = object)
print(arr)
print(arr.dtype)

[{'a': 1} list([1, 2, 3]) 'hello']
object


## **Broadcasting in NumPy**


In [16]:
# Looping Over Arrays in Python

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
 result.append(num ** 2)

print(result) # Output: [1, 4, 9, 16, 25]

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [17]:
# Vectorized Operation

arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2                     # Vectorized operation
print(result)                         # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


In [18]:
# Broadcasting with Scalar

arr = np.array([1, 2, 3, 4, 5])
result = arr + 10 # Broadcasting: 10 is added to all elements
print(result) # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [19]:
# Broadcasting with Arrays of Different Shapes

# Broadcasting with Two Arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2        # Element-wise addition
print(result)               # Output: [11 22 33]

[11 22 33]


In [20]:
# Broadcasting a 2D Array and a 1D Array

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])


result = arr1 + arr2 # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


In [22]:
# Normalizing Data Using Broadcasting


# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)


# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


## **Built in Mathematical Functions in NumPy**


In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
np.mean(arr)

np.float64(2.8722813232690143)

In [25]:
# Standard deviation
np.std(arr)

np.float64(2.8722813232690143)

In [26]:
# variance
np.var(arr)

np.float64(8.25)

In [27]:
# minimum element present
np.min(arr)

np.int64(1)

In [28]:
# maximum element present
np.max(arr)

np.int64(10)

In [29]:
# sum of all elements in an array
np.sum(arr)

np.int64(55)

In [30]:
# Product of all elements in an array
np.prod(arr)

np.int64(3628800)

In [31]:
# median
np.median(arr)

np.float64(5.5)

In [33]:
# percentile of an array
np.percentile(arr, 25)

np.float64(3.25)

In [34]:
# Position of minimum element present in an array
np.argmin(arr)

np.int64(0)

In [35]:
# Position of maximum element present in an array
np.argmax(arr)

np.int64(9)

In [36]:
# correlation coefficient
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([10,20,30,40,50,60,70,80,90,100])

np.corrcoef(arr1, arr2)

array([[1., 1.],
       [1., 1.]])

In [38]:
# unique elements in an array
np.unique(arr)

np.int64(55)

In [39]:
# nth difference of an array
np.diff(arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
# cummulative sum
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [42]:
# Evenly spaced numbers in a range
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [43]:
# natural logarithm of an array
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [44]:
# Exponential of an array
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])